### PR TITLE
Optimize audio requests (10000% improvement)

### LINKED ISSUE #4: Audio URL takes time to fetch (even if audio already synthesized)
## The issue

While scrubbing through the Remotion timeline, the component tries to fetch the URL for the audio for each frame rendered.
This results in the following:
1. No audio for a few seconds, every time the Composition is played from the beginning.
2. Audio server may get numb after too many requests, and stops responding altogether, requiring restarting the preview.

https://user-images.githubusercontent.com/38887390/235301844-6981a9f1-b290-4c31-8977-cc150b422f48.mp4

## Possible workaround

Some way to cache the server response on the client side, using something like React Query or SWR.

### PR DESCRIPTION
**Pull request by thecmdrunner**
Fixes #4 

1. Use React Query to cache the server response.
2. Continues the render only after the query is settled (either success or failed)

## Before

Hundreds of requests being fired while scrubbing the timeline.

https://user-images.githubusercontent.com/38887390/235302464-8dbc81b9-8fdc-4116-865a-d7a30a317e09.mp4

## After

Only 1 request when a composition plays from the start, and zero requests thereafter.

https://user-images.githubusercontent.com/38887390/235302310-d9ab2da3-8415-406c-8dda-9dbaedfb8f12.mp4

### CODE REVIEW

**Comment by thecmdrunner** [comment]
@JonnyBurger Works fine on my side. Can you please try this on Mac aarch_64?

**Review by thecmdrunner — COMMENTED** [review]
Works well during renders and preview, for pre-synthesized as well as non pre-synthesized audios.

Tested on Windows and Linux (x64)

**Comment by JonnyBurger** [comment]
Oh, thanks a lot!
Will try this soon, need to setup everything but it's a good thing if I do 🙂

**Comment by thecmdrunner** [comment]
This was bugging me since day one 😄
The solution was inspired by the use of tRPC in the T3 stack using [`create-t3-app`](https://create.t3.gg/)

**Comment by thecmdrunner** [comment]
@JonnyBurger Does everything seem right? can we go ahead with this merge?

**Comment by JonnyBurger** [comment]
Yes we can!
I did not yet get to try it out but let's not hold it up :) Will still do before launching V4 and get to experience the goated stack!

**Pull request merged**
