### PR TITLE
small changes for v4

### PR DESCRIPTION
**Pull request by patsalv**

### CODE REVIEW

**Comment by thecmdrunner** [comment]
👋 Hey @patsalv, thanks for taking the time to make these awesome changes for v4!
Everything seems right, except for the removal of React Query. This was added because the express server can get overwhelmed with too many requests and then stop responding when scrubbing through the timeline, causing audio to work at all. You can see the **before** and **after** in PR #5

Still, I get why you'd want to remove it and keep the official template as minimal as possible, and if that's the case, please let me know and I'll be happy to merge it 🙂

**Comment by JonnyBurger** [comment]
Hey @thecmdrunner!

We are moving the audio fetching outside of the component with the new V4 architecture, there will be no extraneous requests done! This is the new pattern: https://v4.remotion.dev/docs/data-fetching

Since no more requests are done inside the component, react-query can be eliminated for now.  Hope this works for you!

**Comment by thecmdrunner** [comment]
Absolutely! Love the new direction for data fetching in v4.
@patsalv should I go ahead and merge?

**Comment by JonnyBurger** [comment]
We'll merge it once the final V4 is out, we have a TODO list for all templates: https://github.com/orgs/remotion-dev/projects/5/views/1?query=is%3Aopen+sort%3Aupdated-desc&pane=issue&itemId=29763438

If you are ok with it, nothing to be done, sorry for not informing you of the plan :D

**Comment by JonnyBurger** [comment]
LGTM, we just need to change the version numbers before launch 👍

**Comment by thecmdrunner** [comment]
> LGTM, we just need to change the version numbers before launch +1

and remove React Query from package.json 🙃

**Comment by JonnyBurger** [comment]
Thanks @thecmdrunner for pointing that out! Fixed

**Comment by thecmdrunner** [comment]
@JonnyBurger v4 is finally live! However, using `pnpm` with the latest commit didn't work for me in #8

**Pull request merged**
